### ISSUE TITLE
Firmware procedure

### ISSUE THREAD

**Issue by furmanlukasz** [neuroidss/FreeEEG128-alpha#3]
Is the firmware upload procedure similar to that described for FreeEEG32  --> `FreeEEG32 Flashing via AC6 w/ STM32F103 Blue Pill`?   Is the firmware in: `FreeEEG128-alpha / STM32CubeIDE / workspace_1.5.1 / STM32H743ZI_ads131_80MHz / ` ?

**Comment by dmitry-sukhoruchkin** [comment]
yes, or you can use multi-architecture docker for makefile version https://github.com/neuroidss/FreeEEG128-alpha/blob/main/STM32H743ZI_ads131_80MHz_makefile.tar.gz
